# Created by extended:clip
#
# You can create as many formats as you like.
# Make sure each format has the following things:
# - A unique format name (You f.e. can't have two formats called "member").
# - A set priority (under priority). Higher number = lower priority.
#
# You NEED to have a format called default!
# It will be used, if the player doesn't have any other format available.
#
# You give a format to a player/group with the permission chatformat.<format name>
# You should give the permission chatformat.default to the default group, since this isn't done automatically.
#   
# example for formats:
# formats: 
#   default:
#     priority: 2147483647
#     channel: ''
#     prefix: '&8[&7Guest&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Guest'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Guest'
#     name_tooltip: [] # Set this to [] if you don't want any hovertext.
#     suffix_tooltip: []
#     channel_click_command: ''
#     prefix_click_command: '/ranks'
#     name_click_command: '/msg %player_name% ' # The placeholder will be replaced with the name of the SENDER (Not yours).
#     suffix_click_command: ''
#   Member:
#     priority: 100
#     channel: ''
#     prefix: '&8[&aMember&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Member'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Member'
#     name_tooltip: []
#     suffix_tooltip: []
#     channel_click_command: ''
#     prefix_click_command: '/ranks'
#     name_click_command: '/msg %player_name% '
#     suffix_click_command: ''
check_updates: true
bungeecord:
  enabled: false
  servername: '&8[&cServer&8]'
  join_global: true
relation_placeholders_enabled: true
timestamp_format: MM/dd/yy HH:mm:ss
boolean:
  'true': '&atrue'
  'false': '&cfalse'
ops_use_group_format: false
chat_filter:
  enabled: false
  ignore_case: true
  list:
  - '.; '
  - fuck;fuck
private_message:
  enabled: true
  bungeecord: false
private_message_formats:
  to_sender:
    format: '&7You &e-> &7%recipient_player_name% &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  to_recipient:
    format: '&7%player_name% &e-> &7You &7:'
    tooltip:
    - '%player_server%'
    click_command: '/r '
    chat_color: '&f'
  social_spy: '&8[&cspy&8] &f%player% &e-> &f%recipient%&7:'
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '&7[%vault_groupprefix%&7] '
    name_color: '&b'
    name: '%player_name%'
    suffix: '&7> '
    chat_color: '&f'
    channel_tooltip:
    - ''
    prefix_tooltip:
    - '%player_name%'
    - '&bRank: %vault_group%'
    name_tooltip:
    - ''
    suffix_tooltip:
    - ''
    channel_click_command: /ranks'
    prefix_click_command: /ranks'
    name_click_command: '/msg %player_name% '
    suffix_click_command: ''
